spring:
  application:
    name: music
  datasource:
    url: jdbc:mysql:///test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456


server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 是否开启下划线和驼峰的映射
